#!/bin/bash

set -e

if [ -z "$1" ]
then
	echo "$0 (class) (id)"
	exit 1
fi

CLASS=$1
ID=$2

if [ -z "$2" ]
then
	export ID=$((`cat /.snapshots/$CLASS.id`-1))
fi

for VOL in `ls /.snapshots/$CLASS/$ID`
do
	btrfs subvolume delete /$VOL
	btrfs subvolume snapshot /.snapshots/$CLASS/$ID/$VOL /$VOL
done
